name: Daily Commit

on:
  schedule:
    - cron: '34 8 * * *' 
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} # Use the PAT for authentication        

      - name: 23f2001413@ds.study.iitm.ac.in
        run: |
          git config --global user.name "endlessfantasy"
          git config --global user.email "endless.fantasykawai@gmail.com"
          echo "Daily commit on $(date)" >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily automated commit by GitHub Actions"
          git push
