name: Frequent Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git (23f2001413@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f2001413@ds.study.iitm.ac.in"

      - name: Make a Dummy Change
        run: |
          echo "Last run: $(date --utc)" >> last_run.log  # Ensures a new commit every run
          git add last_run.log

      - name: Commit and Push Changes
        run: |
          git commit -m "Automated commit: $(date --utc)" || echo "No changes to commit"
          git push || echo "Push failed"
